---
name: "Letter of Recommendation"
description: "Kudos to Dan Slinky"
title: "[KUDOS]"
assignees: ["danslinky"]
#projects:
#- project
labels: ["endorsement"]
body:
- type: input
  id: title
  attributes:
    label: Title
    description: "Please enter a title for your letter of recommendation"
    placeholder: "Dan Slinky is the absolute worst colleague I have ever worked with..."
- type: textarea
  id: letter
  attributes:
    label: Letter of Recommendation
    description: "Please say nice things about Dan Slinky"
    value: |
      x.
      y.
      z.
      ...
    render: bash
  validations:
    required: true
- type: dropdown
  id: category
  attributes:
    label: Category
    description: What version of our software are you running?
    options:
      - Friend
      - Boss 
      - Colleague
      - Lover
      - Enemy
    default: 2
  validations:
    required: true
- type: dropdown
  id: employer
  attributes:
    label: Who did Dan Slinky work for?
    multiple: true
    options:
      - Adarga
      - Cookpad
      - Taskrabbit
      - Torchbox
      - Future
      - Capgemini
      - Eurostar
      - Sift
      - CERN
      - UWE
      - Other
- type: input
  id: rickroll
  attributes:
    label: "I have been Rick rolled by Dan Slinky"
    placeholder: "Yes"
    description: "Please enter 'Yes' if you have been Rick rolled by Dan Slinky"
- type: input
  id: rickroll
  attributes:
    label: "Dan contributed to my Safety and Security"
    placeholder: "Yes"
    description: "Did I write on your Facebook wall?"
