authors:
  danslinky:
    name: danslinky
    description: Blog posts by Dan Slinky
    avatar: https://avatars.githubusercontent.com/u/26235577
    slug: danslinky
    url: https://www.danslinky.co.uk/
  klaushergershemier:
    name: klaushergershemier
    description: Blog posts by Klaus Hergershemier
    avatar: https://avatars.githubusercontent.com/u/26235577
    slug: klaushergershemier
    url: https://rtfm.danslinky.co.uk/